
server:
  port: 8090


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: test

#  datasource:
#    url: jdbc:mysql://localhost/TempDatabase
#    username: root
#    password: new-password
#    driver: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect





